---
methods:
  day_after_thanksgiving:
    arguments: year
    ruby: |
      Holidays::Factory::DateCalculator.day_of_month_calculator.call(year, 11, 4, 4) + 1
months:
  1:
    - name: New Year's Day
      regions: [ neolab ]
      mday: 1
      observed: to_weekday_if_weekend(date)
    - name: Martin Luther King, Jr. Day
      regions: [ neolab ]
      week: 3
      wday: 1
  5:
    - name: Memorial Day
      regions: [ neolab ]
      week: -1
      wday: 1
  7:
    - name: Independence Day # fixed
      regions: [ neolab ]
      mday: 4
    - name: Day After Independence Day
      regions: [ neolab ]
      mday: 4
  9:
    - name: Labor Day
      week: 1
      regions: [ neolab ]
      wday: 1
  11:
    - name: Thanksgiving
      regions: [ neolab ]
      week: 4
      wday: 4
    - name: Day after Thanksgiving (Black Friday)
      function: day_after_thanksgiving(year)
      regions: [ neolab ]
  12:
    - name: Christmas Day
      regions: [ neolab ]
      mday: 25
      observed: to_weekday_if_weekend(date)
    - name: Day after Christmas
      regions: [ neolab ]
      mday: 26
    - name: Day after Day after Christmas
      regions: [ neolab ]
      mday: 27
